### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fasteinke** [atakan-topaloglu/2d_gaussian_splatting_colab#1]
Unfortunately, get this error:

Collecting ninja
  Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 2.5 MB/s eta 0:00:00
Installing collected packages: ninja
Successfully installed ninja-1.11.1.1
Processing ./submodules/simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for simple-knn (setup.py) ... error
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
Failed to build simple-knn
ERROR: Could not build wheels for simple-knn, which is required to install pyproject.toml-based projects
Processing ./submodules/diff-surfel-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-surfel-rasterization
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for diff-surfel-rasterization (setup.py) ... error
  ERROR: Failed building wheel for diff-surfel-rasterization
  Running setup.py clean for diff-surfel-rasterization
Failed to build diff-surfel-rasterization
ERROR: Could not build wheels for diff-surfel-rasterization, which is required to install pyproject.toml-based projects

**Comment by atakan-topaloglu** [comment]
Hello, 

Please change the runtime type to a GPU runtime.  
You may connect to a GPU runtime by clicking on the dropdown arrow on top-right (located near RAM and DISK) > change runtime type > Ensure that a T4 GPU or other available GPUs are selected.

Please let me know if the issue persists.

**Comment by fasteinke** [comment]
Sorry about that!! I've been running a few notebooks for GS, and so far it just turned out that a T4 always connected, automatically ... so, just assumed that all was OK in this area, without actually checking - a silly mistake, my bad!

**Comment by atakan-topaloglu** [comment]
No worries! 
It's an easy assumption to make when things have been working smoothly
